### ISSUE TITLE
release points logging

### ISSUE THREAD

**Issue by smkaeser** [WeRobotics/WMP-OnBoard#15]

**Comment by q-golay** [comment]
Just for info: positions of releases are stored in a list in MosquitoMission class during flight, and then saved to a file called “<timestamp>_mosquitoReleasePoints.csv” when mission end is reached (or stopped by tablet). Manual releases triggered during this transition between 2 missions are not stored on the OnBoard (but acknowledge message is still sent to the tablet).

**Comment by smkaeser** [comment]
Thanks! I had to look into the code to find where you store the csv ;)
