### ISSUE TITLE
check if writing is also done multiple times in motor port handler and if not implement it

### ISSUE THREAD

**Issue by smkaeser** [WeRobotics/WMP-OnBoard#16]

**Comment by smkaeser** [comment]
multiple attempts are not in place for writing - implement
multiple attempts in place for getPosition, better put into read function? - change?

**Comment by q-golay** [comment]
https://github.com/WeRobotics/WMP-OnBoard/commit/85ed1d4c8ef32db223130d6dfffaad6f5e7b44dd
